name: Laravel

on:
  push:
    branches: [ "devel" ]
  pull_request:
    branches: [ "devel" ]

jobs:       
  deploy:
    runs-on: self-dev-wew

    steps:
      - name: Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          connect_timeout: 10s
          script: |
            cd /home/devstag/wew/laravel-github-actions
            git checkout -f 
            git pull
