on:
  push:
    branches: [ devel ]
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy PHP Laravel
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          
          script: |
            cd /home/devstag/wew/laravel-github-actions # navigate into the folder
            git pull origin devel # pull the repo
